{
 "title": "Prueba",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=\"node\"},instance)"
    }
   },
   {
    "name": "mem_max",
    "query": {
     "query": "node_memory_MemTotal_bytes{instance=\"$instance\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU%",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM%",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemAvailable_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    { "expr": "$mem_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disco",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$instance\", fstype!~\"tmpfs|overlay\"} \r\n - node_filesystem_avail_bytes{instance=\"$instance\", fstype!~\"tmpfs|overlay\"})\r\n/ 1024 / 1024 / 1024",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=\"$instance\", fstype!~\"tmpfs|overlay\"}) \r\n/ 1024 / 1024 / 1024",
     "legendFormat": "Libre"
    }
   ]
  },
  {
   "title": "Red",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", instance=\"$instance\"}[1m])) / 1024",
     "legendFormat": "Recibido"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\", instance=\"$instance\"}[1m])) / 1024",
     "legendFormat": "Enviado"
    }
   ]
  }
 ]
}