# Stack de Node Exporter
version: '3'
services:
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - target: 9100
        published: ${PORT_NODE_EXPORTER}
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker