# Grafana datasource configuration - Prometheus connection settings
apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: eel59595gd5a8f
    access: proxy
    url: http://${SWARM_MANAGER_IP}:${PORT_PROMETHEUS}
    isDefault: true
    editable: false