# ─────────────────────────────────────────
# Configuración global del entorno
# Modifica estas variables antes de ejecutar deploy.sh
# ─────────────────────────────────────────

# Red LAN
MANAGER_IP=<IP del nodo manager en la red LAN>

# Red Docker Swarm
SWARM_MANAGER_IP=<IP del nodo manager en la red Swarm>
SWARM_WORKER1_IP=<IP del worker1 en la red Swarm>
SWARM_WORKER2_IP=<IP del worker2 en la red Swarm>

# Puertos
PORT_NGINX=80
PORT_JENKINS=8080
PORT_PROMETHEUS=9090
PORT_NODE_EXPORTER=9100
PORT_GRAFANA=3000