# ─────────────────────────────────────────
# Configuración global del entorno
# Modifica estas variables antes de ejecutar deploy.sh
# ─────────────────────────────────────────

# Red LAN
LAN_MANAGER_IP=<IP del nodo manager en la red LAN>

# Red Docker Swarm
SWARM_MANAGER_IP=<IP del nodo manager en la red Swarm>
export SWARM_WORKER1_IP=<IP del worker1 en la red Swarm>
export SWARM_WORKER2_IP=<IP del worker2 en la red Swarm>
# Si necesitas más workers, agrega sus IPs aquí
# export SWARM_WORKER3_IP=<IP del worker3 en la red Swarm>

# Puertos
export PORT_NGINX=80
PORT_JENKINS=8080
export PORT_PROMETHEUS=9090
export PORT_NODE_EXPORTER=9100
PORT_GRAFANA=3000
# Si necesitas más servicios, agrega sus puertos aquí
# PORT_OTRO_SERVICIO=XXXX