# ─────────────────────────────────────────
# Configuración global del entorno
# Modifica estas variables antes de ejecutar deploy.sh
# ─────────────────────────────────────────

# Copyright (C) 2026  Jose Luis Oliver Herranz
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Red LAN
export LAN_MANAGER_IP="<IP del nodo manager en la red LAN>"

# Red Docker Swarm
export SWARM_MANAGER_IP="<IP del nodo manager en la red Swarm>"
export SWARM_WORKER1_IP="<IP del worker1 en la red Swarm>"
export SWARM_WORKER2_IP="<IP del worker2 en la red Swarm>"
# Si necesitas más workers, agrega sus IPs aquí
# export SWARM_WORKER3_IP="<IP del worker3 en la red Swarm>"

# Puertos
export PORT_NGINX=80
export PORT_JENKINS=8080
export PORT_PROMETHEUS=9090
export PORT_NODE_EXPORTER=9100
export PORT_GRAFANA=3000
# Si necesitas más servicios, agrega sus puertos aquí
#export PORT_OTRO_SERVICIO=XXXX