pipeline {
    agent any
    triggers {
        cron('*/5 * * * *')
    }
    stages {
        stage('Desplegar / Actualizar stack') {
            steps {
                // Leemos las variables de global.conf, procesamos el yml y desplegamos
                sh '''
                    source ${WORKSPACE}/config/global.conf
                    envsubst < ${WORKSPACE}/config/swarm/web.yml | docker stack deploy -c - web
                '''
            }
        }
        stage('Verificar réplicas') {
            steps {
                // Comprobamos si el servicio web_nginx existe (el || true evita que la pipeline falle si grep no encuentra nada en el primer instante)
                sh 'docker service ls | grep web_nginx || true'
            }
        }
        stage('Comprobar nodos') {
            steps {
                sh 'docker node ls'
            }
        }
    }
    post {
        always {
            sh '''
                echo "$(date "+%Y-%m-%d %H:%M:%S"): Pipeline ejecutada" >> ${WORKSPACE}/stack_monitor.log
            '''
        }
        success {
            sh '''
                echo "$(date "+%Y-%m-%d %H:%M:%S"): Todos los servicios operativos" >> ${WORKSPACE}/stack_monitor.log
            '''
        }
        failure {
            sh '''
                echo "$(date "+%Y-%m-%d %H:%M:%S"): ERROR - La pipeline falló" >> ${WORKSPACE}/stack_monitor.log
            '''
        }
    }
}